# Generated by Django 3.2.15 on 2023-04-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название', max_length=50, verbose_name='название')),
                ('slug', models.SlugField(help_text='Нормализованное имя', unique=True, verbose_name='слаг')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически выставляется при создании', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Автоматически выставляется при изменении объекта', verbose_name='дата и время последнего редактирования')),
            ],
            options={
                'ordering': ('created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название', max_length=50, verbose_name='название')),
                ('slug', models.SlugField(help_text='Нормализованное имя', unique=True, verbose_name='слаг')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически выставляется при создании', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Автоматически выставляется при изменении объекта', verbose_name='дата и время последнего редактирования')),
                ('text', models.TextField(blank=True, help_text='Опишите стиль, добавьте интересные факты', null=True, verbose_name='описание стиля')),
            ],
            options={
                'ordering': ('created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CategoryExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название', max_length=50, verbose_name='название')),
                ('slug', models.SlugField(help_text='Нормализованное имя', unique=True, verbose_name='слаг')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически выставляется при создании', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Автоматически выставляется при изменении объекта', verbose_name='дата и время последнего редактирования')),
                ('category_base', models.ForeignKey(help_text='Объясните способ носки вещи: верхняя одежда, нижнее бельё, шляпы и т.д.', on_delete=django.db.models.deletion.PROTECT, to='market.categorybase', verbose_name='базовая категория вещи')),
            ],
            options={
                'ordering': ('created', 'name'),
            },
        ),
    ]
