# Generated by Django 3.2.15 on 2023-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_collection_item_itempicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='categorybase',
            name='edited',
            field=models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования'),
        ),
        migrations.AlterField(
            model_name='categoryextended',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='categoryextended',
            name='edited',
            field=models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='edited',
            field=models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='edited',
            field=models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования'),
        ),
        migrations.AlterField(
            model_name='style',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='style',
            name='edited',
            field=models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('items', models.ManyToManyField(help_text='Предметы, которые пользователь добавил в корзину', to='market.Item', verbose_name='предметы в корзине')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
