# Generated by Django 3.2.15 on 2023-04-12 20:30

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_collection_item_itempicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='picture',
            field=models.ImageField(help_text='изображение для галерии товара', upload_to=utils.functions.get_item_images_upload_location, verbose_name='изображение'),
        ),
    ]
