# Generated by Django 3.2.15 on 2023-04-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_itempicture_picture'),
        ('market', '0004_auto_20230413_1621'),
    ]

    operations = [
    ]
