# Generated by Django 3.2.15 on 2023-04-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_auto_20230413_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('sum', models.IntegerField(verbose_name='общая стоимость заказа')),
                ('status', models.CharField(choices=[('0', 'Ожидает'), ('1', 'Принят'), ('2', 'в процессе'), ('3', 'доставка'), ('4', 'выполнен')], default='0', max_length=127)),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_designer', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.item', verbose_name='Заказанная вещь')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
