# Generated by Django 3.2.15 on 2023-04-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_orderclothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='указывает на категорию, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='market.categoryextended', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.IntegerField(help_text='добавьте стоимость вашего товара', verbose_name='стоимость товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='styles',
            field=models.ManyToManyField(help_text='указывает к какому стилю принадлежит товар', related_name='style', to='market.Style', verbose_name='стиль товара'),
        ),
    ]
