# Generated by Django 3.2.15 on 2023-04-13 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_auto_20230413_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL),
        ),
    ]
