# Generated by Django 3.2.15 on 2023-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_ordercustom_orderpicture'),
        ('market', '0007_alter_item_designer'),
    ]

    operations = [
    ]
