# Generated by Django 3.2.15 on 2023-04-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_merge_20230413_1934'),
        ('market', '0008_merge_20230413_1905'),
    ]

    operations = [
    ]
