# Generated by Django 3.2.15 on 2023-04-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20230413_1943'),
        ('market', '0009_merge_20230413_1959'),
    ]

    operations = [
    ]
