# Generated by Django 3.2.15 on 2023-04-13 19:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0009_merge_20230413_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='указывает на категорию, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='market.categoryextended', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Отличный товар'), (4, 'Хороший товар'), (3, 'Обычный товар'), (2, 'Плохой товар'), (1, 'Ужасный товар')], help_text='Ваша оценка', validators=[django.core.validators.MaxValueValidator(5, message='Максимальное значение оценки - 5'), django.core.validators.MinValueValidator(1, message='Минимальное значение оценки - 1')], verbose_name='оценка товара')),
                ('goods', models.TextField(blank=True, help_text='Какие позитивные стороны вы нашли у этого товара', null=True, verbose_name='Достоинства')),
                ('negatives', models.TextField(blank=True, help_text='Какие недостатки вы нашли у этого товара', null=True, verbose_name='Недостатки')),
                ('text', models.TextField(blank=True, help_text='Ваш комментарий после использования этого товара', null=True, verbose_name='Комментарий')),
                ('item', models.ForeignKey(help_text='товар, к которому оставили отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='rating_item', to='market.item', verbose_name='товар')),
                ('user', models.ForeignKey(help_text='пользователь, оставивший отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
