# Generated by Django 3.2.15 on 2023-04-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20230414_2028'),
        ('market', '0010_auto_20230413_2216'),
    ]

    operations = [
    ]
