# Generated by Django 3.2.15 on 2023-04-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20230413_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(help_text='добавьте как можно болеее информативные фотографии', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.item', verbose_name='галерея изображений товара'),
        ),
    ]
