# Generated by Django 3.2.15 on 2023-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_merge_0009_auto_20230414_2028_0010_auto_20230413_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterModelOptions(
            name='categorybase',
            options={'ordering': ('created', 'name'), 'verbose_name': 'тип одежды', 'verbose_name_plural': 'типы одежды'},
        ),
        migrations.AlterModelOptions(
            name='categoryextended',
            options={'ordering': ('created', 'name'), 'verbose_name': 'категория одежды', 'verbose_name_plural': 'категории одежды'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'коллекция', 'verbose_name_plural': 'коллекции'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'вещь', 'verbose_name_plural': 'вещи'},
        ),
        migrations.AlterModelOptions(
            name='itempicture',
            options={'verbose_name': 'фотография вещи', 'verbose_name_plural': 'фотографии вещей'},
        ),
        migrations.AlterModelOptions(
            name='orderclothes',
            options={'verbose_name': 'заказ одежды', 'verbose_name_plural': 'заказы одежды'},
        ),
        migrations.AlterModelOptions(
            name='ordercustom',
            options={'verbose_name': 'заказ кастома', 'verbose_name_plural': 'заказы кастомов'},
        ),
        migrations.AlterModelOptions(
            name='orderpicture',
            options={'verbose_name': 'фотография заказа кастома', 'verbose_name_plural': 'фотографии заказов кастомов'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ('created', 'name'), 'verbose_name': 'стиль', 'verbose_name_plural': 'стили'},
        ),
    ]
