# Generated by Django 3.2.15 on 2023-04-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20230415_1608'),
        ('market', '0015_auto_20230415_1631'),
    ]

    operations = [
    ]
