# Generated by Django 3.2.15 on 2023-04-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20230415_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought',
            field=models.IntegerField(default=0, help_text='сколько раз купили этот товар', verbose_name='куплено раз'),
        ),
    ]
