# Generated by Django 3.2.15 on 2023-04-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_item_bought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='style',
            new_name='styles',
        ),
    ]
