# Generated by Django 3.2.15 on 2023-04-19 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('status', models.CharField(choices=[('wait', 'Ожидает'), ('got', 'Принят'), ('proc', 'в процессе'), ('deli', 'доставка'), ('done', 'выполнен')], default='wait', max_length=127)),
                ('max_price', models.IntegerField(help_text='Бюджет пользователя', verbose_name='максимальная сумма заказа')),
                ('header', models.CharField(help_text='Заголовок заказа', max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, help_text='Опишите дизайн, добавьте какие-то идеи к выбранному изображению', null=True, verbose_name='описание желаемого дизайна')),
            ],
            options={
                'verbose_name': 'заказ кастома',
                'verbose_name_plural': 'заказы кастомов',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Изображение желаемого дизайна', upload_to='uploads/order_pictures', verbose_name='изображение')),
                ('order', models.ForeignKey(help_text='Номер заказа', on_delete=django.db.models.deletion.CASCADE, to='custom.ordercustom', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'фотография заказа кастома',
                'verbose_name_plural': 'фотографии заказов кастомов',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Отличный товар'), (4, 'Хороший товар'), (3, 'Обычный товар'), (2, 'Плохой товар'), (1, 'Ужасный товар')], help_text='Ваша оценка', validators=[django.core.validators.MaxValueValidator(5, message='Максимальное значение оценки - 5'), django.core.validators.MinValueValidator(1, message='Минимальное значение оценки - 1')], verbose_name='оценка')),
                ('goods', models.TextField(blank=True, null=True, verbose_name='Достоинства')),
                ('negatives', models.TextField(blank=True, null=True, verbose_name='Недостатки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(help_text='заказ, к которому оставили отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='custom.ordercustom', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
