# Generated by Django 3.2.15 on 2023-04-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('status', models.CharField(choices=[('wait', 'Ожидает'), ('got', 'Принят'), ('proc', 'в процессе'), ('deli', 'доставка'), ('done', 'выполнен')], default='wait', max_length=127)),
                ('max_price', models.IntegerField(help_text='Бюджет пользователя', verbose_name='максимальная сумма заказа')),
                ('header', models.CharField(help_text='Заголовок заказа', max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, help_text='Опишите дизайн, добавьте какие-то изменения к желаемогу изображению', null=True, verbose_name='описание желаемого дизайна')),
            ],
            options={
                'verbose_name': 'заказ кастома',
                'verbose_name_plural': 'заказы кастомов',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Изображение желаемого дизайна', upload_to='media/uploads/order_pictures', verbose_name='изображение')),
                ('order', models.ForeignKey(help_text='Номер заказа', on_delete=django.db.models.deletion.CASCADE, to='custom.ordercustom', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'фотография заказа кастома',
                'verbose_name_plural': 'фотографии заказов кастомов',
            },
        ),
    ]
