# Generated by Django 3.2.15 on 2023-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustom',
            name='text',
            field=models.TextField(blank=True, help_text='Опишите дизайн, добавьте какие-то идеи к выбранному изображению', null=True, verbose_name='описание желаемого дизайна'),
        ),
    ]
