# Generated by Django 3.2.15 on 2023-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_alter_ordercustompicture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustom',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Нужно ли публиковать ваш заказ, чтобы его видели дизайнеры?', verbose_name='опубликован ли заказ'),
        ),
    ]
