# Generated by Django 3.2.15 on 2023-04-17 14:49

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фото', max_length=200, upload_to=utils.functions.get_item_main_image_location, verbose_name='фото')),
            ],
        ),
    ]
