# Generated by Django 3.2.15 on 2023-04-19 17:56

import auth.managers
import auth.utils
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(blank=True, choices=[('', 'Не указан'), ('male', 'Мужской'), ('female', 'Женский')], default='', help_text='Укажите ваш пол', max_length=127, verbose_name='пол')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_designer', models.BooleanField(default=False, help_text='Отвечает на вопрос, пользователь является дизайнером или нет?', verbose_name='пользователь дизайнер?')),
                ('failed_attemps', models.IntegerField(default=0, verbose_name='Неудачных попыток входа')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('last_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.categoryextended', verbose_name='последняя посещённая категория')),
                ('last_styles', models.ManyToManyField(blank=True, related_name='styles', to='market.Style', verbose_name='последние пять посещённых стилей')),
                ('lovely', models.ManyToManyField(related_name='lovely_designers', to=settings.AUTH_USER_MODEL, verbose_name='Любимые дизайнеры')),
                ('saved', models.ManyToManyField(related_name='saved_items', to='clothes.Item', verbose_name='Сохранённые пользователем вещи')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', auth.managers.UserManager()),
                ('designers', auth.managers.DesignerManager()),
                ('inactive', auth.managers.InactiveUserManager()),
                ('active', auth.managers.ActiveUsersManager()),
            ],
        ),
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='designers/avatars', verbose_name='аватарка дизайнера')),
                ('background', models.ImageField(blank=True, null=True, upload_to='designers/backgrounds', verbose_name='картинка на заднем фоне в профиле дизайнера')),
                ('text', models.TextField(blank=True, help_text='введите информацию о себе', null=True, verbose_name='информация о дизайнере')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс дизайнера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='designer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дизайнер',
                'verbose_name_plural': 'дизайнеры',
            },
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Ключ активации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('expire', models.DateTimeField(default=auth.utils.get_token_expire, verbose_name='Дата и время истечения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
