# Generated by Django 3.2.15 on 2023-04-21 19:34

import auth.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20230421_2233'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='expire',
            field=models.DateTimeField(default=auth.utils.get_token_expire, verbose_name='дата и время истечения'),
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='ключ активации'),
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_attemps',
            field=models.IntegerField(default=0, verbose_name='неудачных попыток входа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lovely',
            field=models.ManyToManyField(related_name='lovely_designers', to=settings.AUTH_USER_MODEL, verbose_name='любимые дизайнеры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(related_name='saved_items', to='clothes.Item', verbose_name='сохранённые пользователем вещи'),
        ),
    ]
