# Generated by Django 3.2.15 on 2023-04-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.categoryextended', verbose_name='Последняя посещённая категория'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_styles',
            field=models.ManyToManyField(to='market.Style', verbose_name='Последние пять посещённых стилей'),
        ),
    ]
