# Generated by Django 3.2.15 on 2023-04-16 15:12

import auth.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.managers.UserManager()),
                ('designers', auth.managers.DesignerManager()),
            ],
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='designer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
