# Generated by Django 3.2.15 on 2023-04-11 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('user_auth', '0002_auto_20230411_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.categoryextended', verbose_name='последняя посещённая категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_styles',
            field=models.ManyToManyField(to='market.Style', verbose_name='последние пять посещённых стилей'),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='designers/avatars', verbose_name='аватарка дизайнера')),
                ('backgroound', models.ImageField(blank=True, null=True, upload_to='designers/backgrounds', verbose_name='картинка на заднем фоне в профиле дизайнера')),
                ('text', models.TextField(blank=True, help_text='введите информацию о себе', null=True, verbose_name='информация о дизайнере')),
                ('balance', models.IntegerField(default=0, verbose_name='знаечение баланса дизайнера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дизайнер',
                'verbose_name_plural': 'дизайнеры',
            },
        ),
    ]
