# Generated by Django 3.2.15 on 2023-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_collection_item_itempicture'),
        ('user_auth', '0003_auto_20230412_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designer',
            new_name='DesignerProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='is_designer',
            field=models.BooleanField(default=False, help_text='Отвечает на вопрос, пользователь является дизайнером или нет?', verbose_name='пользователь дизайнер?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_styles',
            field=models.ManyToManyField(blank=True, null=True, to='market.Style', verbose_name='последние пять посещённых стилей'),
        ),
    ]
