# Generated by Django 3.2.15 on 2023-04-18 23:27

import auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_activationtoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.managers.UserManager()),
                ('designers', auth.managers.DesignerManager()),
                ('inactive', auth.managers.InactiveUserManager()),
            ],
        ),
    ]
