# Generated by Django 3.2.15 on 2023-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_collection_item_itempicture'),
        ('user_auth', '0004_auto_20230412_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_styles',
            field=models.ManyToManyField(blank=True, to='market.Style', verbose_name='последние пять посещённых стилей'),
        ),
    ]
