# Generated by Django 3.2.15 on 2023-04-19 10:36

import auth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.managers.UserManager()),
                ('designers', auth.managers.DesignerManager()),
                ('inactive', auth.managers.InactiveUserManager()),
                ('active', auth.managers.ActiveUsersManager()),
            ],
        ),
        migrations.AddField(
            model_name='activationtoken',
            name='failed_attempls',
            field=models.IntegerField(default=0, verbose_name='Неудачных попыток входа'),
        ),
    ]
