# Generated by Django 3.2.15 on 2023-04-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20230419_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationtoken',
            old_name='failed_attempls',
            new_name='failed_attemps',
        ),
    ]
