# Generated by Django 3.2.15 on 2023-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20230413_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Не указан'), ('male', 'Мужской'), ('female', 'Женский')], default='', help_text='Укажите ваш пол', max_length=127, verbose_name='пол'),
        ),
    ]
