# Generated by Django 3.2.15 on 2023-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
