# Generated by Django 3.2.15 on 2023-04-15 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20230415_2104'),
        ('user_auth', '0009_remove_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lovely',
            field=models.ManyToManyField(related_name='lovely_designers', to=settings.AUTH_USER_MODEL, verbose_name='Любимые дизайнеры'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(related_name='saved_items', to='market.Item', verbose_name='Сохранённые пользователем вещи'),
        ),
    ]
