# Generated by Django 3.2.15 on 2023-04-16 13:43

import django.core.validators
from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('name', models.CharField(max_length=100, verbose_name='Название коллекции')),
                ('text', models.TextField(verbose_name='описание коллекции')),
            ],
            options={
                'verbose_name': 'коллекция',
                'verbose_name_plural': 'коллекции',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Отличный товар'), (4, 'Хороший товар'), (3, 'Обычный товар'), (2, 'Плохой товар'), (1, 'Ужасный товар')], help_text='Ваша оценка', validators=[django.core.validators.MaxValueValidator(5, message='Максимальное значение оценки - 5'), django.core.validators.MinValueValidator(1, message='Минимальное значение оценки - 1')], verbose_name='оценка')),
                ('goods', models.TextField(blank=True, null=True, verbose_name='Достоинства')),
                ('negatives', models.TextField(blank=True, null=True, verbose_name='Недостатки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('name', models.CharField(help_text='Придумайте не длинное название, передающее основные черты товара', max_length=50, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='основная картинка товара')),
                ('cost', models.IntegerField(help_text='добавьте стоимость вашего товара', verbose_name='стоимость товара')),
                ('text', models.TextField(blank=True, help_text='опишите ваш товар', null=True, verbose_name='описание товара')),
                ('bought', models.IntegerField(default=0, help_text='сколько раз купили этот товар', verbose_name='куплено раз')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован?')),
            ],
            options={
                'verbose_name': 'вещь',
                'verbose_name_plural': 'вещи',
            },
        ),
        migrations.CreateModel(
            name='ItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='изображение для галерии товара', upload_to=utils.functions.get_item_images_upload_location, verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'фотография вещи',
                'verbose_name_plural': 'фотографии вещей',
            },
        ),
        migrations.CreateModel(
            name='OrderClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда объект был создан', verbose_name='дата и время создания')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Когда объект в последний раз редактировали', verbose_name='дата и время редактирования')),
                ('status', models.CharField(choices=[('wait', 'Ожидает'), ('got', 'Принят'), ('proc', 'в процессе'), ('deli', 'доставка'), ('done', 'выполнен')], default='wait', max_length=127)),
                ('sum', models.IntegerField(verbose_name='общая стоимость заказа')),
            ],
            options={
                'verbose_name': 'заказ одежды',
                'verbose_name_plural': 'заказы одежды',
            },
        ),
    ]
