# Generated by Django 3.2.15 on 2023-04-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclothes',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_clothes_designer', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='orderclothes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.item', verbose_name='Заказанная вещь'),
        ),
        migrations.AddField(
            model_name='orderclothes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_clothes_user', to=settings.AUTH_USER_MODEL, verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(help_text='добавьте как можно болеее информативные фотографии', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothes.item', verbose_name='галерея изображений товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='указывает на категорию, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='market.categoryextended', verbose_name='категория товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(help_text='показывает участвует ли товар в каких-либо коллекциях', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clothes.collection', verbose_name='коллекция, в которой есть этот товар'),
        ),
        migrations.AddField(
            model_name='item',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_designer', to=settings.AUTH_USER_MODEL, verbose_name='Дизайнер вещи'),
        ),
        migrations.AddField(
            model_name='item',
            name='styles',
            field=models.ManyToManyField(help_text='указывает к какому стилю принадлежит товар', related_name='style', to='market.Style', verbose_name='стиль товара'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='item',
            field=models.ForeignKey(help_text='товар, к которому оставили отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clothes.item', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(help_text='пользователь, оставивший отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='collection',
            name='designer',
            field=models.ForeignKey(help_text='Укажите кто создал эту коллекцию', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='дизайнер коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='styles',
            field=models.ManyToManyField(related_name='item_styles', to='market.Style', verbose_name='стиль коллекции'),
        ),
    ]
