# Generated by Django 3.2.15 on 2023-04-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс'), ('childish', 'Детский')], default='unisex', help_text='Кто будет носить эту вещь?', max_length=15, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='item',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_designer', to=settings.AUTH_USER_MODEL, verbose_name='дизайнер вещи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Придумайте не длинное название, передающее основные черты товара', max_length=50, verbose_name='название товара'),
        ),
    ]
