# Generated by Django 3.2.15 on 2023-04-17 18:24

from django.db import migrations, models
import django.db.models.deletion
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cart'),
        ('clothes', '0004_auto_20230417_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='указывает на категорию, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='market.categoryextended', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='фото'),
        ),
    ]
