# Generated by Django 3.2.15 on 2023-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20230416_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс'), ('childish', 'Детский')], default='unisex', help_text='Кто будет носить эту вещь?', max_length=15, verbose_name='пол'),
        ),
    ]
