# Generated by Django 3.2.15 on 2023-04-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20230417_2124'),
        ('clothes', '0005_item_gender'),
    ]

    operations = [
    ]
