# Generated by Django 3.2.15 on 2023-04-18 14:41

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_merge_0005_auto_20230417_2124_0005_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='фото'),
        ),
    ]
