# Generated by Django 3.2.15 on 2023-04-21 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0006_alter_item_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название коллекции'),
        ),
        migrations.AlterField(
            model_name='item',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_designer', to=settings.AUTH_USER_MODEL, verbose_name='дизайнер вещи'),
        ),
        migrations.AlterField(
            model_name='orderclothes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.item', verbose_name='заказанная вещь'),
        ),
    ]
