# Generated by Django 3.2.15 on 2023-04-18 18:37

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_auto_20230418_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempicture',
            name='picture',
        ),
        migrations.AddField(
            model_name='itempicture',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
    ]
