# Generated by Django 3.2.15 on 2023-04-19 18:50

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20230418_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='default/default.png', help_text='Загрузите фото', max_length=255, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default/default.png', help_text='Загрузите фото', max_length=255, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='image',
            field=models.ImageField(default='default/default.png', help_text='Загрузите фото', max_length=255, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
    ]
