# Generated by Django 3.2.15 on 2023-04-20 17:53

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_auto_20230419_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='defaults/item.png', help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=255, null=True, upload_to=utils.functions.get_item_main_image_location, verbose_name='обложка'),
        ),
    ]
