# Generated by Django 3.2.15 on 2023-04-21 19:33

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, help_text='Приложите свое вложение к сообщению', null=True, upload_to=utils.functions.get_message_image_upload_location, verbose_name='приложение к сообщению'),
        ),
    ]
